### ISSUE TITLE
dataset_split

### ISSUE THREAD

**Issue by zhantt626** [Zhang-xie/WiGr#1]
hello:
      I think your work is very interesting and I have done some research these days. I constructed the ARIL dataset with the source_data num_batch size of 43. Then the source_data failed after splitting with the function torch.utils.data.random_split, as shown below. It was found that the train_set's dimention is only (34x52x192), however it should be (34x24x52x192+34x6x52x192). Have you encountered similar situations before? Looking forward to your recovery!

Prototypical_1DResNet.py", line 172
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by elegantCai** [comment]
This is so brilliant work！But there is no code for data preprocessing，could author provide it？Thanks so much
